const cars = [
  {
    id: 1,
    name: "Koenigsegg",
    type: "Sport",
    img: require("../images/car.png"),
    gasoline: "90L",
    capacity: 2,
    price: "$99.00",
    discount: null,
    isLiked: false,
  },
  {
    id: 2,
    name: "Nissan GT - R",
    type: "Sport",
    img: require("../images/car (1).png"),
    gasoline: "80L",
    capacity: 2,
    price: "$80.00",
    discount: "$100.00",
  },
  {
    id: 3,
    name: "Rolls - Royce",
    type: "Sedan",
    img: require("../images/car (2).png"),
    gasoline: "70L",
    capacity: 4,
    price: "$96.00",
    discount: null,
  },
  {
    id: 4,
    name: "Nissan GT - R",
    type: "Sport",
    img: require("../images/car (3).png"),
    gasoline: "80L",
    capacity: 2,
    price: "$80.00",
    discount: "$100.00",
  },
  {
    id: 5,
    name: "All New Rush",
    type: "SUV",
    img: require("../images/car (4).png"),
    gasoline: "70L",
    capacity: 6,
    price: "$72.00",
    discount: "$80.00",
  },

  {
    id: 6,
    name: "CR  - V",
    type: "SUV",
    img: require("../images/car (5).png"),
    gasoline: "80L",
    capacity: 6,
    price: "$80.00",
    discount: null,
  },
  {
    id: 7,
    name: "All New Terios",
    type: "SUV",
    img: require("../images/car (6).png"),
    gasoline: "90L",
    capacity: 6,
    price: "$47.00",
    discount: null,
  },
  {
    id: 8,
    name: "CR  - V",
    type: "SUV",
    img: require("../images/car (7).png"),
    gasoline: "80L",
    capacity: 6,
    price: "$80.00",
    discount: null,
  },
  {
    id: 9,
    name: "MG ZX Exclusice",
    type: "Hatchback",
    img: require("../images/car (8).png"),
    gasoline: "70L",
    capacity: 4,
    price: "$76.00",
    discount: "$80.00",
  },
  {
    id: 10,
    name: "New MG ZS",
    type: "SUV",
    img: require("../images/car (9).png"),
    gasoline: "80L",
    capacity: 6,
    price: "$80.00",
    discount: null,
  },
  {
    id: 11,
    name: "MG ZX Excite",
    type: "Hatchback",
    img: require("../images/car (10).png"),
    gasoline: "90L",
    capacity: 4,
    price: "$74.00",
    discount: null,
  },
  {
    id: 12,
    name: "New MG ZS",
    type: "SUV",
    img: require("../images/car (11).png"),
    gasoline: "80L",
    capacity: 6,
    price: "80.00",
    discount: null,
  },
];

export default cars;
